# Generated by Django 3.1 on 2020-08-18 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Appointments',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Dr_name', models.CharField(max_length=50)),
                ('Dr_Adress', models.CharField(max_length=200)),
                ('Dr_specialization', models.CharField(max_length=30)),
                ('Dr_timeings', models.TimeField()),
                ('Patient_name', models.CharField(max_length=50)),
                ('Appt_Date', models.DateField()),
                ('user_id', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Feedbacks',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=20)),
                ('Email', models.CharField(max_length=50)),
                ('Message', models.CharField(max_length=1000)),
            ],
        ),
    ]
